import { FlatList,Image, StyleSheet, Text, View, ScrollView, TextInput, Button,TouchableOpacity,RefreshControl } from 'react-native'
import React, { useContext,useEffect, useState } from 'react'
import { SafeAreaView } from 'react-native-safe-area-context';
import { COLORS, SIZES, FONTS, icons, images } from "../constants"
import LinearGradient from 'react-native-linear-gradient';
import { GlobalContext } from '../datafolder/GlobalState';



import PushNotification from "react-native-push-notification";

const wait = (timeout) => {
  return new Promise(resolve => setTimeout(resolve, timeout));
}




const sleep = ms => new Promise(
  resolve => setTimeout(resolve, ms)
);





sendNotification = () => {
  //console.log('pressed first')
  PushNotification.localNotification({
    title: "You have detect Pothole",
    message: "Pothole Notification",
  });
}



/*
<FlatList
          data={data}
          keyExtractor={({ id }, index) => id}
          renderItem={({ item }) => (
            <Text>{item.title}, {item.releaseYear}</Text>
          )}
        />

*/

const Notification = (Location,dateTime) => {
  PushNotification.localNotification({
    /* Android Only Properties /
    channelId: 'channel-id', // (required) channelId, if the channel doesn't exist, notification will not trigger.
    / iOS and Android properties */
    //id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    title: 'Pothole Detected', // (optional)
    message: `Pothole Detected in ${Location} at ${dateTime}` ,  // (required)
  });
};


const Log = () => {
  const [refreshing, setRefreshing] = React.useState(false);
  const [isLoading, setLoading] = useState(true);
  const [data, setData] = useState([]);
  const [text,onChangeText] = useState();
  const {das,setDas} = useContext(GlobalContext)
  const {yes,setYes} = useContext(GlobalContext)

  const [newDataCount,setnewDataCount] = useState(null)
  const [dataCount, setdataCount] = useState(null)

  function updateIP (text){
    setDas(text)
    console.log(das)
  }
  const getPots = async() =>{
    setDas(text)
    try{
      
      const response = await fetch(`http://192.168.22.3:9191/GetPotholes`)
      const dat = await response.json();
      setData(dat);
      setYes(false)
      setYes(false)
      setnewDataCount(dat.length)
      if (newDataCount>dataCount){
        Notification (data[data.length-1]["location"],data[data.length-1]["dateTime"]);
        console.log('W')

        setdataCount(newDataCount)
        setdataCount(newDataCount)  
        
      }
      //console.log(data[data.length-1]["location"])
      setdataCount(newDataCount)
      //console.log(dataCount)
    } catch(error){
      console.error(error);
    }finally {
      setLoading(false);
    }
      await sleep(1000);
  }


  useEffect(()=>{
    getPots()
  },[data,das]) 


  

  return(
    <SafeAreaView style={styles.container}>
      { yes && <TextInput
        style={{height: 40,backgroundColor: 'azure', fontSize: 20,margin:20}}  
        onChangeText={onChangeText}
        value={text}
        editable = {yes}
        />}
        {yes && 
        <Button
          onPress={()=>updateIP(text)}
          title="Update IP Address of RPI"
          color="#841584"
          
        />}
      <View style={styles.headerBar}>
          <Text style={styles.txtBar}> Log Screen</Text>
      </View>
          <View>
              <Text style={styles.txtHeader}>List of Potholes</Text>
          </View>
          <FlatList 
                // contentContainerStyle={{
                //   padding : 20,
                //   backgroundColor: "white"
                // }}
                data={data}
                keyExtractor={({id}, index) => id}

                contentContainerStyle={{ paddingBottom: "20%",padding:20,paddingRight:50,paddingLeft:50}}

                refreshControl={
                  <RefreshControl 
                    refreshing={refreshing}
                    onRefresh={getPots}/>
                  }




                renderItem= {({item}) =>(

                  
          <View>
                    <View style={styles.itemList}>
                      <Image 
                      source={{uri: `data:image/png;base64,${item.blobData}`}}
                      style={{width: 130, height: 150, margin:5}}/>
                      
                      <View style={{paddingLeft:15}}>
                        <Text style={styles.txtName}>Location: {item.location}</Text>
                        <Text style={styles.txtName}>dateTime: {item.dateTime}</Text>
                        <Text style={styles.txtName}>Latitude: {item.latitude}</Text>
                        <Text style={styles.txtName}>Longtitude: {item.longitude}</Text>

                  <TouchableOpacity
                    style={[styles.shadow, { marginTop: 2, width: '50%', height: 50, alignItems: 'center', justifyContent: 'center' }]}
                    >
                    <LinearGradient
                        style={{ height: '50%', width: '100%', alignItems: 'center', justifyContent: 'center', borderRadius: 15 }}
                        colors={['#FE9001', '#010101']}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 0 }}
                    >
                        <Text style={{ color: COLORS.white, ...FONTS.h3 }}>Send Email</Text>
                    </LinearGradient>
                  </TouchableOpacity>
                      </View>

                    </View> 
                
          </View>
          )}/>
          <View style={styles.headerBar}/>
    </SafeAreaView>
  );
};

export default Log;

const styles = StyleSheet.create({



  container:{
    backgroundColor:"#e1e1e1",

  },

  
  headerBar: {
    padding:20,
    backgroundColor:"#e1e1e1",
    flex: 1,
    padding: 20
  },
  txtBar:{
    fontsize: 50,
    fontWeight: "bold",
    textAlign: "center",
  },
  txtHeader:{
    fontsize: 18,
    fontWeight: "bold",
    textAlign: "center"
  },
  itemList:{
    paddingVertical: 30,
    borderBottomColor: "#e2e2e",
    borderBottomWidth: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row'
  },
  txtName:{
    fontsize: 16,
    textAlign: "justify",
    fontWeight: "bold"
  },
});